config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :messages

  resources :chats
  resources :qchats, controller: 'q_chats', as: 'qchats'

  resources :queries, except: [:index] do
    collection do
      get :metadata
      get :data
    end
  end
  get '/query', to: 'queries#index'

  devise_for :users, controllers: {
    sessions: 'custom_sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :data_sources do
    member do
      get :connect
    end

    resources :tables, only: [:show]
    resources :queries

    resources :chats do
      resources :messages, only: %i[create destroy]
    end

    resources :qchats, controller: 'q_chats', as: 'qchats' do
      resources :messages, only: %i[create destroy]
    end
  end

  get '/chat', to: 'chats#index'
  get '/qchat', to: 'q_chats#index', as: 'qchat_root'

  get 'users/settings', to: 'users#settings', as: 'user_settings'
  patch 'users/settings', to: 'users#settings'

  root to: 'home#index'
  get '/swatch', to: 'home#swatch'

  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => '/cable'
end

app/models/q_chat.rb
# frozen_string_literal: true

class QChat < Chat
end

app/controllers/q_chats_controller.rb
# frozen_string_literal: true

# QChatsController manages the CRUD operations for QChat resources.
# It ensures that user authentication is required and sets up the
# appropriate data source before performing actions.
class QChatsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_data_source
  before_action :set_qchat, only: %i[show edit update destroy]

  def index
    @chat = @data_source.qchats.order(created_at: :desc).first
    @chat = @data_source.qchats.create(name: 'Chat') if @chat.blank?

    render :show
  end

  def show
    @chat = @data_source.qchats.friendly.find(params[:id])
  end

  def new
    @chat = @data_source.qchats.create(name: 'Chat')
    redirect_to '/qchat'
  end

  def create
    @chat = @data_source.qchats.new(qchat_params)
    if @chat.save
      redirect_to data_source_chat_path(@data_source, @chat), notice: 'Chat was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @chat.update(qchat_params)
      redirect_to data_source_chat_path(@data_source, @chat), notice: 'Chat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to data_source_chats_path(@data_source), notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_data_source
    @data_source = DataSource.friendly.find(params[:data_source_id] || current_user.connected_data_source.id)
  end

  def set_qchat
    @chat = @data_source.qchats.friendly.find(params[:id])
  end

  def qchat_params
    params.permit(:name)
  end
end

app/views/q_chats/_chat.html.erb
<div id="<%= dom_id chat %>">
  <p>
    <strong>Name:</strong>
    <%= chat.name %>
  </p>

  <p>
    <strong>Data source:</strong>
    <%= chat.data_source_id %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= chat.slug %>
  </p>

</div>

app/views/q_chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :data_source_id, style: "display: block" %>
    <%= form.text_field :data_source_id %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/q_chats/edit.html.erb
<h1>Editing chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Show this chat", @chat %> |
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/q_chats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chat</h1>

app/views/q_chats/new.html.erb
<h1>New chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/q_chats/show.html.erb
<!-- app/views/chats/show.html.erb -->
<%= render partial: 'queries/grid' %>
<style>
  .tall {
    height: calc(100% - 50px);
    display: flex;
    flex-direction: column;
  }
</style>
<div class="container-fluid tall ">
  <div class="row">
    <div class="col">
      <h1 class="mb-4">QChat</h1>
    </div>
    <div class="col text-end">
      <%= link_to new_qchat_path, class: "btn btn-dark btn-plus btn-lg", data: { bs_toggle: "tooltip", bs_placement: "bottom", bs_custom_class: "custom-tooltip", bs_title: "New Chat" }, title: "New Chat" do %>
        <i class="bi bi-pencil-square"></i>
      <% end %>
    </div>
  </div>
  <div class="row scrollable-content" id="messages-scrollbox">
    <div class="col-12 ">
      <div id="messages">
        <% if @chat.messages.any? %>
          <%= render partial: 'messages/qmessage', collection: @chat.messages, as: :message %>
        <% else %>
          <div class="card p-4 m-4 rounded-4 col-6">
            <h3>Welcome to Query Chat!</h3>
            <h4 style="line-height: 1.7;" >I'm your AI assistant, here to help you interact with your database effortlessly. Just tell me what you're looking for, and I'll generate the SQL queries and provide the data you need. Whether you have specific questions, need to explore your data, or want insights, I'm here to assist you. Ask me anything, and let's get started!</h5>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <%= turbo_frame_tag "new_message" do %>
        <%= form_with model: [@data_source, @chat, Message.new], url: data_source_chat_messages_path(@data_source, @chat), local: false, data: { turbo: "true" } do |form| %>
          <%= form.hidden_field :role, value: 'user' %>
          <%= form.text_field :content, class: 'form-control border-1', placeholder: "Message AI" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<script>
  document.addEventListener("turbo:load", () => {
    const scrollboxDiv = document.getElementById("messages-scrollbox");

    if (scrollboxDiv) {
      scrollboxDiv.scrollTop = scrollboxDiv.scrollHeight;
    } else {
      console.error('Element with ID "messages-scrollbox" not found.');
    }

    <% @chat.messages.each do |message| %>
      <% if message.role == 'assistant' %>
          initializeGrid(
                'id<%= message.id %>',
                '<%= message.preview || message.sql %>'
          );
      <% end %>
    <% end %>
  });
  document.addEventListener('turbo:submit-end', (event) => {
  const form = event.target;


  if (form.querySelector('input[name="message[content]"]')) {
    form.querySelector('input[name="message[content]"]').value = '';
  }
  });
</script>