config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :messages

  resources :chats
  resources :qchats, controller: 'q_chats', as: 'qchats'

  resources :queries, except: [:index] do
    collection do
      get :metadata
      get :data
    end
  end
  get '/query', to: 'queries#index'

  devise_for :users, controllers: {
    sessions: 'custom_sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :data_sources do
    member do
      get :connect
    end

    resources :tables, only: [:show]
    resources :queries

    resources :chats do
      resources :messages, only: %i[create destroy]
    end

    resources :qchats, controller: 'q_chats', as: 'qchats' do
      resources :messages, only: %i[create destroy]
    end
  end

  get '/chat', to: 'chats#index'
  get '/qchat', to: 'q_chats#index', as: 'qchat_root'

  get 'users/settings', to: 'users#settings', as: 'user_settings'
  patch 'users/settings', to: 'users#settings'

  root to: 'home#index'
  get '/swatch', to: 'home#swatch'

  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => '/cable'
end

app/models/chat.rb
# frozen_string_literal: true

# The Chat model represents a conversation session within the application.
# It includes functionality for generating URL-friendly slugs based on the chat name using the FriendlyId gem.
# A Chat belongs to a DataSource and can have many Messages. It requires a name to be present.
class Chat < ApplicationRecord
  self.inheritance_column = :type

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :data_source
  has_many :messages, dependent: :destroy

  validates :name, presence: true

  scope :excluding_qchats, -> { where(type: nil) }

  def qchat?
    is_a?(QChat)
  end
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

# app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_data_source
  before_action :set_chat, only: %i[show edit update destroy]

  def index
    @chat = @data_source.chats.excluding_qchats.order(created_at: :desc).first
    @chat = @data_source.chats.create(name: 'Chat') if @chat.blank?

    render :show
  end

  def show
    @chat = @data_source.chats.friendly.find(params[:id])
  end

  def new
    @chat = @data_source.chats.create(name: 'Chat')
    redirect_to '/chat'
  end

  def create
    @chat = @data_source.chats.new(chat_params)
    if @chat.save
      redirect_to data_source_chat_path(@data_source, @chat), notice: 'Chat was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @chat.update(chat_params)
      redirect_to data_source_chat_path(@data_source, @chat), notice: 'Chat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to data_source_chats_path(@data_source), notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_data_source
    @data_source = DataSource.friendly.find(params[:data_source_id] || current_user&.connected_data_source&.id)
  end

  def set_chat
    @chat = @data_source.chats.friendly.find(params[:id])
  end

  def chat_params
    params.require(:chat).permit(:name)
  end
end

app/helpers/chats_helper.rb
# frozen_string_literal: true

module ChatsHelper
end

app/views/chats/show.html.erb
<!-- app/views/chats/show.html.erb -->
<%= render partial: 'queries/grid' %>
<style>
  .tall {
    height: calc(100% - 50px);
    display: flex;
    flex-direction: column;
  }
</style>
<div class="container-fluid tall ">
  <div class="row">
    <div class="col">
      <h1 class="mb-4">Chat</h1>
    </div>
    <div class="col text-end">
      <%= link_to new_chat_path, class: "btn btn-dark btn-plus btn-lg", data: { bs_toggle: "tooltip", bs_placement: "bottom", bs_custom_class: "custom-tooltip", bs_title: "New Chat" }, title: "New Chat" do %>
        <i class="bi bi-pencil-square"></i>
      <% end %>
    </div>
  </div>
  <div class="row scrollable-content" id="messages-scrollbox">
    <div class="col-12 ">
      <div id="messages">
        <% if @chat.messages.any? %>
          <%= render @chat.messages %>
        <% else %>
          <div class="card p-4 m-4 rounded-4 col-6">
            <h3>Welcome to your Virtual DBA!</h3>
            <h4 style="line-height: 1.7;" >I am your AI-powered Database Administrator, here to assist you with all your data needs. Ask me anything!<br><br>Need to understand the structure of your database?<br>Have missing keys or foreign key issues?<br>Looking to optimize your queries, code, or frameworks?<br>Want advice on database security or performance tuning?<br><br>I'm here to help with all that and more!</h5>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <%= turbo_frame_tag "new_message" do %>
        <%= form_with model: [@data_source, @chat, Message.new], url: data_source_chat_messages_path(@data_source, @chat), local: false, data: { turbo: "true" } do |form| %>
          <%= form.hidden_field :role, value: 'user' %>
          <%= form.text_field :content, class: 'form-control border-1', placeholder: "Message AI" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<script>
  const scrollToBottom = () => {
    const scrollboxDiv = document.getElementById("messages-scrollbox");

    if (scrollboxDiv) {
      scrollboxDiv.scrollTop = scrollboxDiv.scrollHeight;
    } else {
      console.error('Element with ID "messages-scrollbox" not found.');
    }
  };

  document.addEventListener("turbo:load", () => {
    scrollToBottom();

    <% @chat.messages.each do |message| %>
      <% if message.role == 'assistant' %>
          initializeGrid(
                'id<%= message.id %>',
                '<%= message.preview || message.sql %>'
          );
      <% end %>
    <% end %>
  });

  document.addEventListener('turbo:submit-end', (event) => {
    const form = event.target;

    if (form.querySelector('input[name="message[content]"]')) {
      form.querySelector('input[name="message[content]"]').value = '';
    }

    scrollToBottom();
  });

  document.addEventListener('turbo:before-stream-render', (event) => {
    const target = event.target;

    if (target.dataset.scroll === "true") {
      scrollToBottom();
    }
  });
</script>