config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :messages

  resources :chats
  resources :qchats, controller: 'q_chats', as: 'qchats'

  resources :queries, except: [:index] do
    collection do
      get :metadata
      get :data
    end
  end
  get '/query', to: 'queries#index'

  devise_for :users, controllers: {
    sessions: 'custom_sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :data_sources do
    member do
      get :connect
    end

    resources :tables, only: [:show]
    resources :queries

    resources :chats do
      resources :messages, only: %i[create destroy]
    end

    resources :qchats, controller: 'q_chats', as: 'qchats' do
      resources :messages, only: %i[create destroy]
    end
  end

  get '/chat', to: 'chats#index'
  get '/qchat', to: 'q_chats#index', as: 'qchat_root'

  get 'users/settings', to: 'users#settings', as: 'user_settings'
  patch 'users/settings', to: 'users#settings'

  root to: 'home#index'
  get '/swatch', to: 'home#swatch'

  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => '/cable'
end

app/views/layouts/sidebar/_accordion_item.html.erb
<div class="accordion-item">
  <h2 class="accordion-header">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= title.sub(' ','_') %>" aria-expanded="false" aria-controls="collapse<%= title.sub(' ','_') %>">
      <i class="fs-4 <%= icon_class %> <%= text_muted %>"></i> <span class="ms-2 d-none d-sm-inline <%= text_muted %>"><%= title %></span>
    </button>
  </h2>
  <div id="collapse<%= title.sub(' ','_') %>" class="accordion-collapse collapse" data-bs-parent="#accordianBar">
    <div class="accordion-body">
      <%= render "layouts/sidebar/#{title.downcase.sub(' ','_')}" %>
    </div>
  </div>
</div>

app/views/layouts/sidebar/_chats.html.erb
<% if connected? %>
  <ul class="list-group list-group-flush">
    <% current_user.connected_data_source.chats.excluding_qchats.each do |chat| %>
      <% if chat.name != "Chat" %>
        <li class="list-group-item">
          <a href="<%= data_source_chat_path(chat.data_source, chat) %>" class="nav-link px-0"><%= chat.name %></a>
        </li>
      <% end%>
    <% end%>
  </ul>
<% end %>

app/views/layouts/sidebar/_data_sources.html.erb
<% if user_signed_in? %>
  <div>
    <ul class="list-group list-group-flush">
      <% current_user.data_sources.each do |data_source| %>
        <% next unless data_source.id.present? %>
        
          <% icon_color = data_source.connected? ? "success" : "danger" %>
          <li class="list-group-item d-flex justify-content-between align-items-center border-0 border-bottom">
            <a href="<%= connect_data_source_path(data_source) %>" class="nav-link d-flex align-items-center">
              <i class="me-1 bi bi-circle-fill text-<%= icon_color %>"></i>
              <%= data_source.name %>
            </a>
            <span>
              <a href="<%= edit_data_source_path(data_source) %>" class="nav-link">
                <i class="bi bi-pencil-fill text-warning">
                </i>
              </a>
              <%= link_to data_source_path(data_source), method: :delete, data: { turbo_method: "delete", turbo_confirm: 'Are you sure?' }, class: 'nav-link text-danger' do %>
                <i class="bi bi-trash-fill"></i>
              <% end %></span>
          </li>
        
      <% end%>
      <li class="list-group-item" ><a href="<%= new_data_source_path %>" class="nav-link"><i class="me-1 bi bi-plus-circle-fill "></i>New Data Source</a></li>
    </ul>
  </div>
<% end %>

app/views/layouts/sidebar/_main.html.erb
<div class="p-1 ">
  <a href="/" class="text-white text-decoration-none">
    <center>
      <h1 class="mt-2">ThinkDB</h1>
    </center>
  </a>
  <div class="btn-group w-100 p-2" role="group" aria-label="">
    <a href="/qchat" class="btn btn-outline-light">
      <i class="fs-4 bi-chat-square-text <%= text_muted %>"></i><span class="ms-2  <%= text_muted %>">QChat</span>
    </a>
    <a href="/query" class="btn btn-outline-light">
      <i class="fs-4 bi-question-circle <%= text_muted %>"></i><span class="ms-2  <%= text_muted %>">Query</span>
    </a>
    <a href="/chat" class="btn btn-outline-light">
      <i class="fs-4 bi-chat-dots <%= text_muted %>"></i><span class="ms-2  <%= text_muted %>">Chat</span>
    </a>
  </div>
</div>
<hr class="p-0 m-0">
<div class="accordion accordion-flush" id="accordianBar">
  <%= render partial: 'layouts/sidebar/accordion_item', locals: { title: 'Data Sources', text_muted: text_muted, icon_class: 'bi-server' } %>
  <%= render partial: 'layouts/sidebar/accordion_item', locals: { title: 'Tables', text_muted: text_muted, icon_class: 'bi-table' } %>
  <%= render partial: 'layouts/sidebar/accordion_item', locals: { title: 'Queries', text_muted: text_muted, icon_class: 'bi-question-circle-fill' } %>
  <%= render partial: 'layouts/sidebar/accordion_item', locals: { title: 'QChats', text_muted: text_muted, icon_class: 'bi-chat-square-text-fill ' } %>
  <%= render partial: 'layouts/sidebar/accordion_item', locals: { title: 'Chats', text_muted: text_muted, icon_class: 'bi-chat-dots-fill' } %>
</div>
<hr class="p-0 m-0">
<% if user_signed_in? %>
  <div class="dropdown p-2 floatz border">
    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
      <% if current_user.image %><img src="<%= current_user.image %>" width="30" height="30" class="rounded-circle"><% end %>
      <span class="d-none d-sm-inline mx-1"><%= current_user.name || current_user.email %></span>
    </a>
    <ul class="dropdown-menu  text-small shadow" aria-labelledby="dropdownUser1">
      <li><a class="dropdown-item" href="<%= user_settings_path %>">Settings</a></li>
      <% if current_user.admin? %>
        <li><a class="dropdown-item" href="<%= sidekiq_web_path %>" target="_blank">Sidekiq</a></li>
      <% end %>
      <li>
        <hr class="dropdown-divider">
      </li>
      <li><a class="dropdown-item" data-method="delete" href="/users/sign_out"">Sign out</a></li>
    </ul>
  </div>
<% else %>
  <div class="dropdown p-2 floatz border">
    <a href="<%= new_user_session_path %>" class="d-flex align-items-center text-white text-decoration-none ">
      <i class="fs-4 bi-person text-muted"></i>
      <span class="d-none d-sm-inline mx-1">Sign In</span>
    </a>
  </div>
<% end %>

app/views/layouts/sidebar/_qchats.html.erb
<% if connected? %>
  <ul class="list-group list-group-flush">
    <% current_user.connected_data_source.qchats.each do |chat| %>
      <% if chat.name != "Chat" %>
        <li class="list-group-item">
          <a href="<%= data_source_qchat_path(chat.data_source, chat) %>" class="nav-link px-0"><%= chat.name %></a>
        </li>
      <% end%>
    <% end%>
  </ul>
<% end %>

app/views/layouts/sidebar/_queries.html.erb
<% if connected? %>
  <ul class="list-group list-group-flush">
    <% current_user.connected_data_source.queries.each do |query| %>
      <li class="list-group-item">
        <a href="<%= data_source_query_path(query.data_source, query) %>" class="nav-link px-0"><%= query.name %></a>
      </li>
    <% end%>
  </ul>
<% end %>

app/views/layouts/sidebar/_tables.html.erb
<% if connected? %>
  <ul class="list-group list-group-flush">
    <% current_user.connected_data_source.tables.each do |table| %>
      <li class="list-group-item">
         <a href="<%= data_source_table_path(table.data_source, table) %>" class="nav-link px-0" data-turbo-frame="table-content"><%= table.name %></a>
      </li>
    <% end%>
  </ul>
<% end %>